# Generated by Django 3.2.15 on 2022-09-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Associados',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
